/**
 * customerCopy.ts
 *
 * Centralised customer-facing wording layer.
 *
 * All presentation components should import labels and phrases from here so
 * that copy never drifts across screens.  A single edit here propagates to
 * every surface.
 *
 * PR2 language rules:
 *   • No "Fail", "Rejected", "Constraint", "Not suitable", "Fix Required"
 *   • Replace with softer, consequence-led equivalents
 *   • Keep physics honest; translate into lived effect
 *   • Messaging shape: Affirm → Align → Explain behaviour → Guide
 *
 * These maps cover presentation labels only.  Engine-internal identifiers
 * (e.g. LimiterSeverity 'fail') are implementation details and are unaffected.
 */

// ─── Option / verdict suitability status ─────────────────────────────────────

/** Labels for OptionCardV1['status'] in customer-facing comparison panels. */
export const OPTION_STATUS_LABEL: Record<string, string> = {
  viable:   'Best fit',
  caution:  'Possible with upgrades',
  rejected: 'Less suited to this use',
};

/** Icon for OptionCardV1['status'] in customer-facing comparison panels. */
export const OPTION_STATUS_ICON: Record<string, string> = {
  viable:   '✅',
  caution:  '⚠️',
  rejected: '○',
};

// ─── Verdict status ───────────────────────────────────────────────────────────

/** Labels for VerdictV1['status'] shown on the recommendation card / report. */
export const VERDICT_STATUS_LABEL: Record<string, string> = {
  good:    'Recommended',
  caution: 'Possible with caveats',
  fail:    'Less suited to this setup',
};

// ─── Limiter / constraint severity ───────────────────────────────────────────

/**
 * Customer-facing labels for LimiterSeverity ('fail' | 'warn' | 'info').
 *
 * These replace harsh engineering terms in customer-visible panels.
 * The underlying severity values in the engine contracts are unchanged.
 */
export const SEVERITY_LABEL: Record<string, string> = {
  fail: 'Needs attention',
  warn: 'Something to be aware of',
  info: 'Info',
};

/**
 * Summary verdict label for a group of limiters (e.g. constraints header).
 * 'action'  — at least one 'fail' limiter present
 * 'review'  — at least one 'warn' limiter, no fails
 * 'ok'      — no active limiters
 */
export const LIMITER_GROUP_LABEL: Record<'action' | 'review' | 'ok', string> = {
  action: 'Needs attention',
  review: 'Worth a check',
  ok:     'All good',
};

// ─── Combi / stored risk ──────────────────────────────────────────────────────

/**
 * Combi DHW risk labels for customer-facing panels.
 * Replaces "Fail — simultaneous demand not met" etc.
 */
export const COMBI_RISK_LABEL: Record<string, string> = {
  fail: 'Performance may be limited by simultaneous demand',
  warn: 'Borderline — performance may vary at peak demand',
  pass: 'Simultaneous demand is within range',
};

/**
 * Stored DHW risk label for customer-facing panels.
 */
export const STORED_RISK_LABEL: Record<string, string> = {
  fail: 'Performance may be limited',
  warn: 'Worth monitoring',
  pass: 'Within expected range',
};

// ─── Constraint / limiter summary phrases ────────────────────────────────────

/**
 * Short summary lines for the VerdictStrip constraint tile.
 *
 * 'blocking'   — severity === 'fail'
 * 'advisory'   — severity === 'warn'
 * 'clear'      — no active limiters
 */
export const CONSTRAINT_SUMMARY: Record<'blocking' | 'advisory' | 'clear', string> = {
  blocking: 'Something to be aware of',
  advisory: 'Worth checking',
  clear:    'No known limitations',
};

// ─── Confidence level display ─────────────────────────────────────────────────

export const CONFIDENCE_LABEL: Record<string, string> = {
  high:   '🟢 High confidence',
  medium: '🟡 Medium confidence',
  low:    '🔴 Low confidence',
};

// ─── Portal / report intro phrases ───────────────────────────────────────────

/** Heading for the "why this suits" section — portal + report. */
export const PORTAL_WHY_HEADING = 'Why this works well for your home';

/** Intro for the portal footer. */
export const PORTAL_FOOTER_COPY =
  'This recommendation was generated by Atlas — a physics-based heating ' +
  'system assessment tool. For questions about your recommendation, contact ' +
  'the engineer who carried out your survey.';

/** Label for the "required changes" section in portal / report. */
export const PORTAL_CHANGES_HEADING = 'What the installation would involve';

// ─── Banned phrasing guard (development aid) ─────────────────────────────────

/**
 * Words that must not appear in customer-facing rendered copy.
 *
 * This list is used by copy regression tests to verify that the wording layer
 * itself does not inadvertently re-introduce banned terms.
 *
 * Note: engine-internal identifiers (e.g. severity: 'fail') are not
 * customer-visible text and are therefore not subject to this constraint.
 */
export const BANNED_CUSTOMER_PHRASES: ReadonlyArray<string> = [
  'Fix Required',
  'Not suitable',
  'Not Suitable',
  'Does not meet criteria',
  'Constraint failing',
  'Fail — simultaneous demand not met',
  'Combi cannot meet simultaneous demand',
  'Recommendation withheld',
];
