/**
 * customerCopy.ts
 *
 * Centralised customer-facing wording layer.
 *
 * All presentation components should import labels and phrases from here so
 * that copy never drifts across screens.  A single edit here propagates to
 * every surface.
 *
 * PR2 language rules:
 *   • No "Fail", "Rejected", "Constraint", "Not suitable", "Fix Required"
 *   • Replace with softer, consequence-led equivalents
 *   • Keep physics honest; translate into lived effect
 *   • Messaging shape: Affirm → Align → Explain behaviour → Guide
 *
 * These maps cover presentation labels only.  Engine-internal identifiers
 * (e.g. LimiterSeverity 'fail') are implementation details and are unaffected.
 */

// ─── Option / verdict suitability status ─────────────────────────────────────

/** Labels for OptionCardV1['status'] in customer-facing comparison panels. */
export const OPTION_STATUS_LABEL: Record<string, string> = {
  viable:   'Best fit',
  caution:  'Possible with upgrades',
  rejected: 'Less suited to this use',
};

/** Icon for OptionCardV1['status'] in customer-facing comparison panels. */
export const OPTION_STATUS_ICON: Record<string, string> = {
  viable:   '✅',
  caution:  '⚠️',
  rejected: '○',
};

// ─── Verdict status ───────────────────────────────────────────────────────────

/** Labels for VerdictV1['status'] shown on the recommendation card / report. */
export const VERDICT_STATUS_LABEL: Record<string, string> = {
  good:    'Recommended',
  caution: 'Possible with caveats',
  fail:    'Less suited to this setup',
};

// ─── Limiter / constraint severity ───────────────────────────────────────────

/**
 * Customer-facing labels for LimiterSeverity ('fail' | 'warn' | 'info').
 *
 * These replace harsh engineering terms in customer-visible panels.
 * The underlying severity values in the engine contracts are unchanged.
 */
export const SEVERITY_LABEL: Record<string, string> = {
  fail: 'Needs attention',
  warn: 'Something to be aware of',
  info: 'Info',
};

/**
 * Summary verdict label for a group of limiters (e.g. constraints header).
 * 'action'  — at least one 'fail' limiter present
 * 'review'  — at least one 'warn' limiter, no fails
 * 'ok'      — no active limiters
 */
export const LIMITER_GROUP_LABEL: Record<'action' | 'review' | 'ok', string> = {
  action: 'Needs attention',
  review: 'Worth a check',
  ok:     'All good',
};

// ─── Combi / stored risk ──────────────────────────────────────────────────────

/**
 * Combi DHW risk labels for customer-facing panels.
 * Replaces "Fail — simultaneous demand not met" etc.
 */
export const COMBI_RISK_LABEL: Record<string, string> = {
  fail: 'Performance may be limited by simultaneous demand',
  warn: 'Borderline — performance may vary at peak demand',
  pass: 'Simultaneous demand is within range',
};

/**
 * Stored DHW risk label for customer-facing panels.
 */
export const STORED_RISK_LABEL: Record<string, string> = {
  fail: 'Performance may be limited',
  warn: 'Worth monitoring',
  pass: 'Within expected range',
};

// ─── Constraint / limiter summary phrases ────────────────────────────────────

/**
 * Short summary lines for the VerdictStrip constraint tile.
 *
 * 'blocking'   — severity === 'fail'
 * 'advisory'   — severity === 'warn'
 * 'clear'      — no active limiters
 */
export const CONSTRAINT_SUMMARY: Record<'blocking' | 'advisory' | 'clear', string> = {
  blocking: 'Something to be aware of',
  advisory: 'Worth checking',
  clear:    'No known limitations',
};

// ─── Confidence level display ─────────────────────────────────────────────────

export const CONFIDENCE_LABEL: Record<string, string> = {
  high:   '🟢 High confidence',
  medium: '🟡 Medium confidence',
  low:    '🔴 Low confidence',
};

// ─── Portal / report intro phrases ───────────────────────────────────────────

/** Heading for the "why this suits" section — portal + report. */
export const PORTAL_WHY_HEADING = 'Why this works well for your home';

/** Intro for the portal footer. */
export const PORTAL_FOOTER_COPY =
  'This recommendation was generated by Atlas — a physics-based heating ' +
  'system assessment tool. For questions about your recommendation, contact ' +
  'the engineer who carried out your survey.';

/** Label for the "required changes" section in portal / report. */
export const PORTAL_CHANGES_HEADING = 'What the installation would involve';

// ─── PR3 — Customer-chosen option copy ───────────────────────────────────────

/**
 * Label for the "choose this option" affordance on option cards.
 * Used on recommendation cards, comparison surfaces, and the portal.
 */
export const CHOOSE_OPTION_LABEL = 'Choose this option';

/**
 * Label shown when a customer has already chosen an option.
 * Confirms their selection without being confrontational.
 */
export const CHOSEN_OPTION_CONFIRMED_LABEL = 'Your chosen option';

/**
 * Label for the "use in comparison" affordance — a softer entry point
 * when the customer hasn't committed to a choice yet.
 */
export const USE_IN_COMPARISON_LABEL = 'Use this option in the comparison';

/**
 * Framing block copy for when the customer-chosen option differs from
 * the Atlas recommendation.
 *
 * Structure: Affirm → Align → Explain behaviour → Guide
 * (reuses the PR2 copy framework — no separate tone)
 */
export const CHOSEN_OPTION_FRAMING = {
  /** Opening affirmation — never confrontational. */
  affirm: "I can see why this option appeals.",
  /** Alignment sentence — links choice to their priorities. */
  align:  "It fits with what matters to you.",
  /**
   * Behaviour intro — leads into the physics-honest consequence.
   * The specific consequence is populated from option-level data,
   * not hardcoded here.
   */
  behaviourIntro: "In your home, the main thing shaping performance is",
  /**
   * Guide sentence — steers back toward the recommended option
   * without dismissing the customer's choice.
   */
  guide: "That's why the recommended option gives you more headroom here.",
  /** Section heading for the chosen-option framing block. */
  heading: "Your chosen option",
  /** Sub-heading clarifying the recommended option is still available. */
  recommendedStillAvailable:
    "The recommended option is still shown below for comparison.",
} as const;

/**
 * Real-world behaviour consequence phrases for customer-chosen options.
 *
 * These describe daily-use implications in lived-experience terms.
 * Used when the customer has chosen an option that differs from the
 * Atlas recommendation.
 */
export const CHOSEN_OPTION_BEHAVIOUR_NOTES: Record<string, string> = {
  simultaneous_demand:
    'Performance may feel more limited when more than one outlet is in use.',
  stored_vs_combi:
    'This keeps things compact, but stored hot water would give you more flexibility at busier times.',
  lighter_demand:
    'This can still work well for lighter demand.',
  reduced_cycling:
    'This option reduces boiler cycling, which helps efficiency over time.',
};

// ─── PR4 — Real-world behaviour card copy ────────────────────────────────────

/**
 * Customer-facing label for each behaviour outcome tier.
 *
 * Outcome tiers are derived from engine BehaviourOutcome values:
 *   strong / acceptable → works_well
 *   limited             → works_with_limits
 *   poor                → best_for_lighter_use
 */
export const BEHAVIOUR_OUTCOME_LABEL: Record<'works_well' | 'works_with_limits' | 'best_for_lighter_use', string> = {
  works_well:           'Works well',
  works_with_limits:    'Works with some limits',
  best_for_lighter_use: 'Better for lighter use',
};

/**
 * Customer-facing note for the recommended option in the divergence comparison.
 * Describes what the recommended option delivers in a given scenario.
 *
 * Keyed by BehaviourOutcome (engine-internal value) for precision.
 */
export const BEHAVIOUR_OUTCOME_RECOMMENDED_NOTE: Record<string, string> = {
  strong:     'Gives you more headroom for this kind of use.',
  acceptable: 'Should handle this comfortably for most households.',
  limited:    'Handles this within typical use, though busy periods may feel tighter.',
  poor:       'Better suited to lighter-use homes on this front.',
};

/**
 * Customer-facing note for the chosen (alternative) option in the divergence comparison.
 * Describes the practical consequence of choosing a different option for a given scenario.
 *
 * Keyed by BehaviourOutcome (engine-internal value) for precision.
 */
export const BEHAVIOUR_OUTCOME_CHOSEN_NOTE: Record<string, string> = {
  strong:     'Your chosen option handles this equally well.',
  acceptable: 'Should still work well for most everyday scenarios.',
  limited:    'Keeps things compact, but performance may feel more limited at busier times.',
  poor:       'May feel more limited here — worth discussing with your engineer.',
};

/**
 * Customer-facing label for the primary limiting factor in a behaviour scenario.
 * Translates engine-internal constraint identifiers into plain-English explanations.
 */
export const BEHAVIOUR_LIMITING_FACTOR_LABEL: Record<string, string> = {
  mains:               'The incoming mains supply is the main thing shaping this result.',
  storage:             'Stored hot water volume is the key factor here.',
  instantaneous_output: 'The heat source output capacity shapes this result.',
  recovery:            'How quickly the system can reheat is the key factor here.',
  distribution:        'Pipework distribution pressure shapes this result.',
};

// ─── PR5 — Inline explainer link copy ────────────────────────────────────────

/**
 * Customer-facing label for inline "Learn why" links that open the
 * explainers overlay at the relevant explainer for a behaviour card.
 *
 * These labels appear on RealWorldBehaviourCards when a limiting factor
 * maps to an available educational explainer.
 */
export const EXPLAINER_LINK_LABEL = 'Learn why';

/**
 * Aria label for inline explainer links — includes the explainer title
 * for accessibility. Use with string interpolation:
 *   EXPLAINER_LINK_ARIA(explainer.title)
 */
export const EXPLAINER_LINK_ARIA = (title: string): string =>
  `Learn why: ${title}`;

// ─── Banned phrasing guard (development aid) ─────────────────────────────────

/**
 * Words that must not appear in customer-facing rendered copy.
 *
 * This list is used by copy regression tests to verify that the wording layer
 * itself does not inadvertently re-introduce banned terms.
 *
 * Note: engine-internal identifiers (e.g. severity: 'fail') are not
 * customer-visible text and are therefore not subject to this constraint.
 */
export const BANNED_CUSTOMER_PHRASES: ReadonlyArray<string> = [
  'Fix Required',
  'Not suitable',
  'Not Suitable',
  'Does not meet criteria',
  'Constraint failing',
  'Fail — simultaneous demand not met',
  'Combi cannot meet simultaneous demand',
  'Recommendation withheld',
  'You chose against advice',
  'Override',
  'Overridden',
  'instantaneous hot water',
];
