/**
 * explainers.ts
 *
 * Shared type definitions for customer-facing physics explainer components.
 *
 * These types are used by DrivingStylePhysicsExplainer and its associated
 * lane-state generation module.  They are intentionally kept separate from
 * engine types so explainer logic can be tested and consumed independently.
 */

// ─── System focus ─────────────────────────────────────────────────────────────

/** Which heating system type a lane represents. */
export type DrivetrainId = 'combi' | 'system' | 'mixergy' | 'heatpump';

/**
 * Which lane(s) the component should highlight.
 * 'all' renders all four with equal prominence.
 */
export type SystemFocus = DrivetrainId | 'all';

// ─── Input context ────────────────────────────────────────────────────────────

/**
 * Occupancy usage signature — maps to OccupancySignature in the engine
 * but is kept as a standalone union here so the explainer has no hard
 * dependency on engine schema types.
 */
export type ExplainerOccupancySignature = 'professional' | 'steady' | 'shift';

/** Controls quality that influences the Mixergy / hyper-miler lane smoothness. */
export type ExplainerControlsQuality = 'basic' | 'good' | 'excellent';

// ─── Lane state ───────────────────────────────────────────────────────────────

/**
 * Discrete motion states for a driving lane token.
 * Used to drive CSS animation classes without coupling to a JS animation lib.
 */
export type LaneMotionState =
  | 'idle'       // not yet started
  | 'launching'  // initial acceleration burst
  | 'cruising'   // steady forward progress
  | 'reversing'  // brief backward roll (combi purge)
  | 'braking'    // sudden slowdown (combi second-tap event)
  | 'warning'    // simultaneous-demand alert active
  | 'finished';  // crossed finish line

/** An event that happens during the race simulation. */
export interface LaneEvent {
  /** Phase in the animation at which this event fires (0–1 progress fraction). */
  atProgress: number;
  /** Short label shown as an overlay badge at the event moment. */
  label: string;
  /** Which lane this event applies to. */
  lane: DrivetrainId;
}

/** Relative energy consumption ranking (lower = more efficient). */
export type EnergyRank = 1 | 2 | 3 | 4;

/**
 * Full state snapshot for a single driving lane.
 * Generated by buildDrivingStyleLaneStates() and consumed declaratively by
 * the component.
 */
export interface LaneState {
  id: DrivetrainId;
  /** Display name shown above the lane. */
  label: string;
  /** Short caption shown below the lane. */
  caption: string;
  /** Current motion state that drives CSS animation class. */
  motionState: LaneMotionState;
  /**
   * Normalised progress along the track (0 = start, 1 = finish line).
   * Gas lanes converge near 1.0; heat pump finishes slightly later.
   */
  progress: number;
  /**
   * Remaining energy level (0–1, where 1 = full tank).
   * Combi drains fastest; heat pump drains slowest.
   */
  energyLevel: number;
  /**
   * Relative energy-use rank at the finish.
   * 1 = least energy consumed; 4 = most.
   */
  energyRank: EnergyRank;
  /** Whether this lane should show a concurrent-demand warning badge. */
  showConcurrentWarning: boolean;
}

// ─── Explainer props ──────────────────────────────────────────────────────────

/** Props accepted by DrivingStylePhysicsExplainer. */
export interface DrivingStylePhysicsExplainerProps {
  /**
   * Which system to emphasise.  Defaults to 'all' — all four lanes shown with
   * equal prominence.
   */
  systemFocus?: SystemFocus;
  /**
   * Number of concurrent hot-water outlets in the household.
   * When >= 2, the combi lane shows a slowdown + warning badge.
   */
  peakConcurrentOutlets?: number;
  /**
   * Household occupancy pattern used to weight animation speed/smoothness.
   */
  occupancySignature?: ExplainerOccupancySignature;
  /** Quality of heating controls — influences Mixergy lane smoothness. */
  controlsQuality?: ExplainerControlsQuality;
  /** Whether a Mixergy cylinder is installed (makes lane 3 the Mixergy lane). */
  hasMixergy?: boolean;
  /**
   * Compact / static mode — renders final states without animation.
   * Used for PDF/report contexts and reduced-motion fallback.
   */
  compact?: boolean;
}

// ─── Builder inputs ───────────────────────────────────────────────────────────

/**
 * Inputs consumed by buildDrivingStyleLaneStates().
 * Mirrors DrivingStylePhysicsExplainerProps but with resolved defaults so
 * callers can use the function independently of the component.
 */
export interface DrivingStyleExplainerInput {
  peakConcurrentOutlets: number;
  occupancySignature: ExplainerOccupancySignature;
  controlsQuality: ExplainerControlsQuality;
  hasMixergy: boolean;
}
