import { ENGINE_VERSION, ASSUMPTION_VERSION } from '../contracts/versions';

export default function ModellingNotice() {
  return (
    <div className="modelling-notice">
      <strong>Modelling Notice</strong>
      <p>
        Results shown are generated by the Atlas physics engine using declared assumptions and survey inputs.
        They represent estimated performance under modelled conditions and do not replace a professional site
        survey or commissioning assessment.
      </p>
      <p className="modelling-notice-meta">
        Engine version: v{ENGINE_VERSION} &nbsp;·&nbsp; Assumption set: {ASSUMPTION_VERSION}
      </p>
    </div>
  );
}
