/**
 * InstallationScopePackV1.ts — Installer-ready scope bundles.
 *
 * Purpose:
 *   Group generated specification lines into reusable surveyor-facing
 *   installation packs that can be accepted, edited, or expanded.
 *
 * Explicit boundaries:
 *   - NOT customer-facing
 *   - NOT quote pricing
 *   - NOT compliance pass/fail
 *   - NOT final engineering design
 *
 * The review workflow:
 *   suggested → accepted | edited | rejected | needs_check
 *
 * Each pack carries three audience-facing summaries:
 *   customerSummary  — plain-language scope, no technical detail
 *   engineerSummary  — technical intent for the installing engineer
 *   officeSummary    — admin/commercial scope note for the office team
 */

import type { SpecificationLineType } from '../specLines/SpecificationLineV1';

// ─── Review status ────────────────────────────────────────────────────────────

/**
 * Workflow state for a scope pack as reviewed by a surveyor or office user.
 *
 *   suggested   — auto-generated by Atlas; awaiting human review
 *   accepted    — accepted as-is
 *   edited      — accepted with modifications to included lines or summaries
 *   rejected    — not applicable for this job; no lines included
 *   needs_check — flagged for further verification before acceptance
 */
export type ScopePackReviewStatus =
  | 'suggested'
  | 'accepted'
  | 'edited'
  | 'rejected'
  | 'needs_check';

// ─── Contract ─────────────────────────────────────────────────────────────────

/**
 * InstallationScopePackV1
 *
 * A single surveyor-facing installation scope bundle derived from the
 * generated specification lines and the implementation pack.
 *
 * Generated deterministically from:
 *   - buildInstallationScopePacks(specificationLines, implementationPack)
 *
 * NOT customer-facing. NOT quote pricing. NOT compliance pass/fail.
 * NOT final engineering design.
 */
export interface InstallationScopePackV1 {
  /** Machine-readable pack identifier, e.g. 'standard_unvented_cylinder_install'. */
  readonly packId: string;

  /** Human-readable pack label, e.g. 'Standard Unvented Cylinder Installation'. */
  readonly label: string;

  /**
   * Short description of what this scope pack covers and when it applies.
   * Engineer/office-facing — not for customers.
   */
  readonly description: string;

  /**
   * Scenario type identifiers this pack applies to, e.g. ['system_unvented', 'regular_unvented'].
   * Empty array means the pack can apply to any scenario type.
   */
  readonly appliesToScenarioTypes: readonly string[];

  /**
   * Specification line types that are always required in this pack.
   * These line types must be present for the pack to be applicable.
   */
  readonly requiredLineTypes: readonly SpecificationLineType[];

  /**
   * Specification line types that are optional (add-on) for this pack.
   * These are surfaced as optional extensions the surveyor can add.
   */
  readonly optionalLineTypes: readonly SpecificationLineType[];

  /**
   * Specification line IDs included in this pack by default.
   * Sourced from the generated spec lines — not independently generated.
   */
  readonly defaultIncludedLineIds: readonly string[];

  /**
   * Specification line IDs within pack scope but excluded by default.
   * Surfaced as available add-ons the surveyor can opt in to.
   */
  readonly defaultExcludedLineIds: readonly string[];

  /**
   * Plain-language summary for customer-facing use.
   * Must avoid technical jargon, qualifications framing, and regulatory language.
   * Must comply with atlas-terminology.md conventions.
   */
  readonly customerSummary: string;

  /**
   * Technical summary for the installing engineer.
   * May include component identifiers, sizing notes, and compliance triggers.
   */
  readonly engineerSummary: string;

  /**
   * Administrative/commercial scope note for the office team.
   * Should cover what work is in scope, required qualifications, and any
   * provisionals that need pricing confirmation.
   */
  readonly officeSummary: string;

  /** Current review workflow state. */
  readonly reviewStatus: ScopePackReviewStatus;
}
