/**
 * validateAiCustomerSummary.ts — Validates AI-rewritten customer summary text
 * against the locked CustomerSummaryV1.
 *
 * Rules:
 *   - Reject if the recommended system label is absent from the text.
 *   - Reject if another system appears near "recommended", "best", "right choice", or "should".
 *   - Reject if the text includes scope items not present in the locked summary.
 *   - Reject if the text invents pressure/flow/heat-loss claims not present in the summary.
 *   - Reject if the text contradicts decision.recommendedScenarioId.
 *
 * If validation fails, callers should fall back to the deterministic
 * plainEnglishDecision from CustomerSummaryV1.
 */

import type { CustomerSummaryV1 } from '../../contracts/CustomerSummaryV1';

// ─── Other system labels ──────────────────────────────────────────────────────

/**
 * All customer-visible system labels used in the recommendation engine.
 * Used to detect when AI text mentions a non-recommended system as preferred.
 */
const ALL_SYSTEM_LABELS: string[] = [
  'combi boiler',
  'system boiler',
  'regular boiler',
  'heat-only boiler',
  'air source heat pump',
  'heat pump',
  'ashp',
];

/** Phrases that indicate a recommendation claim. */
const RECOMMENDATION_TRIGGER_PHRASES =
  /\b(recommended|best|right choice|should)\b/i;

/**
 * Invented physics claim patterns — terms that signal fabricated technical facts.
 * These claims require measured survey data and must never be generated by AI.
 */
const INVENTED_PHYSICS_PATTERNS = [
  /\b\d+\s*(bar|l\/min|litres?\s*per\s*minute|lpm|kw|kilowatts?|metres?|meters?)\b/i,
  /\bheat[\s-]?loss\s+of\b/i,
  /\bflow\s+rate\s+of\b/i,
  /\bmains\s+pressure\s+of\b/i,
];

// ─── Validation result ────────────────────────────────────────────────────────

export interface AiSummaryValidationResult {
  /** True when the text passes all validation gates. */
  valid: boolean;
  /** Reasons for rejection, empty when valid. */
  reasons: string[];
}

// ─── Validator ────────────────────────────────────────────────────────────────

/**
 * validateAiCustomerSummary
 *
 * Checks whether AI-rewritten text is consistent with the locked
 * CustomerSummaryV1. Returns a validation result with all failure reasons.
 *
 * Callers should discard the AI text and fall back to
 * lockedSummary.plainEnglishDecision when valid === false.
 */
export function validateAiCustomerSummary(
  text: string,
  lockedSummary: CustomerSummaryV1,
): AiSummaryValidationResult {
  const reasons: string[] = [];
  const lowerText = text.toLowerCase();
  const lowerLabel = lockedSummary.recommendedSystemLabel.toLowerCase();

  // ── Gate 1: recommended system label must be present ─────────────────────
  if (!lowerText.includes(lowerLabel)) {
    reasons.push(
      `Selected system label "${lockedSummary.recommendedSystemLabel}" is absent from AI text`,
    );
  }

  // ── Gate 2: no other system near a recommendation phrase ──────────────────
  // Split on sentence boundaries for context proximity testing.
  const sentences = text.split(/[.!?\n]+/);
  for (const sentence of sentences) {
    const lowerSentence = sentence.toLowerCase();
    if (!RECOMMENDATION_TRIGGER_PHRASES.test(lowerSentence)) continue;

    for (const otherLabel of ALL_SYSTEM_LABELS) {
      if (otherLabel === lowerLabel) continue;
      // Skip labels that are substrings of the recommended label (e.g. "heat pump"
      // is contained within "air source heat pump" — not a different system).
      if (lowerLabel.includes(otherLabel)) continue;
      if (lowerSentence.includes(otherLabel)) {
        reasons.push(
          `AI text mentions non-selected system "${otherLabel}" near a recommendation phrase: "${sentence.trim()}"`,
        );
        break; // one violation per sentence is enough
      }
    }
  }

  // ── Gate 3: no scope items not in locked summary ─────────────────────────
  const allLockedScope = new Set<string>([
    ...lockedSummary.includedNow.map((s) => s.toLowerCase()),
    ...lockedSummary.optionalUpgrades.map((s) => s.toLowerCase()),
    ...lockedSummary.futureReady.map((s) => s.toLowerCase()),
  ]);

  // Only check for clearly invented scope: words that appear alongside
  // "include", "install", "fit", "replace", "add", "upgrade" in the AI text
  // but are not in the locked scope. We use a conservative check — only flag
  // explicit nouns not in the locked scope when adjacent to action verbs.
  const inventedScopePattern =
    /\b(include[sd]?|install(?:ed|ing)?|fit(?:ted)?|replac(?:e[sd]?|ing)|add(?:ed|ing)?|upgrad(?:e[sd]?|ing))\s+(?:a\s+|an\s+|the\s+)?([a-z][a-z\s\-]{2,40}?)(?:\s+(?:to|for|in|on|at|with|and)|[.,;]|$)/gi;
  let match: RegExpExecArray | null;
  while ((match = inventedScopePattern.exec(lowerText)) !== null) {
    const candidate = match[2].trim();
    // Only flag if the candidate is longer than 4 chars (noise filter)
    // and not found in the locked scope set (exact or prefix)
    if (candidate.length > 4) {
      const found = [...allLockedScope].some(
        (s) => s.includes(candidate) || candidate.includes(s.split(' ')[0]),
      );
      if (!found) {
        reasons.push(
          `AI text may include scope item not in locked summary: "${candidate}"`,
        );
        // Limit to 3 violations to avoid noise in the reasons list
        if (reasons.filter((r) => r.includes('scope item not in')).length >= 3) {
          break;
        }
      }
    }
  }

  // ── Gate 4: no invented physics claims ────────────────────────────────────
  for (const pattern of INVENTED_PHYSICS_PATTERNS) {
    if (pattern.test(text)) {
      reasons.push(
        `AI text contains invented technical measurement matching "${pattern.source}"`,
      );
    }
  }

  return {
    valid: reasons.length === 0,
    reasons,
  };
}
